# Generated by Django 4.2.7 on 2025-12-29 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="分类名称")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="URL标识"),
                ),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="商品名称")),
                ("slug", models.SlugField(max_length=200, verbose_name="URL标识")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="products/%Y/%m/%d", verbose_name="商品图片"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="商品描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="库存")),
                ("available", models.BooleanField(default=True, verbose_name="是否可用")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["id", "slug"], name="shop_produc_id_f21274_idx"
                    ),
                    models.Index(fields=["name"], name="shop_produc_name_a2070e_idx"),
                    models.Index(
                        fields=["-created"], name="shop_produc_created_ef211c_idx"
                    ),
                ],
            },
        ),
    ]
